CREATE TABLE IF NOT EXISTS "CustomRole" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "canEditEmployer" BOOLEAN NOT NULL DEFAULT true,
  "canEditClient" BOOLEAN NOT NULL DEFAULT true,
  "canEditWorkType" BOOLEAN NOT NULL DEFAULT true,
  "canEditNotes" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "CustomRole_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "CustomRole_name_key" ON "CustomRole"("name");
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "customRoleId" TEXT;
ALTER TABLE "User" ADD CONSTRAINT IF NOT EXISTS "User_customRoleId_fkey"
  FOREIGN KEY ("customRoleId") REFERENCES "CustomRole"("id") ON DELETE SET NULL ON UPDATE CASCADE;
